dbt_cinemaparadiso:
  outputs:
    dev:
      dataset: cinema_paradiso
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_GCP_PROJECT_CINEMA') }}"
      threads: 10
      type: bigquery
  target: dev