name: 'dbt_cinemaparadiso'
version: '1.0.0'

profile: 'dbt_cinemaparadiso'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_cinemaparadiso:
    cleaning:
      +materialized: view
    cleaned:
      +materialized: table
    before_analysis:
      +materialized: view
    for_analysis:
      +materialized: table
